language: php
php:
  - 5.3
  - 5.4
  - 5.5
before_script:
    - COMPOSER_ROOT_VERSION=dev-master composer --prefer-source --dev install
script: phpunit tests
notifications:
  email:
    - alessandro.nadalin@gmail.com
